### ISSUE TITLE
Get module working

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/term_body_class#3]
Helping to fix some bugs and get this module working.

**Comment by ghost** [comment]
@olafgrabienski Here you go: https://github.com/backdrop-contrib/term_body_class/pull/4

- The `if ($form_id == 'field_ui_field_edit_form') {` check wasn't needed since you're implementing `hook_form_FORM_ID_alter()`.
- You needed to add your checkbox to the `settings` part of the form (and update other parts of the code to reference the `settings` part too).
- `classes_array` has been replaced with `classes`.

**Comment by olafgrabienski** [comment]
Thanks a lot for your help and the useful explanation, @BWPanda ! The PR got the module working.

I guess, the unneeded `if` and the `settings` part are a matter of experience with Backdrop. However, after changing the module file by myself, I also ran it through Coder Upgrade for a comparison. Interestingly, the change from `classes array` to `classes` wasn't covered there. (Have posted it here: https://github.com/backdrop-contrib/coder_upgrade/issues/1#issuecomment-698318217)
